# Generated by Django 4.2.2 on 2023-07-01 15:28

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(height_field=70, upload_to=job.models.image_upload, width_field=70),
        ),
    ]
